### ISSUE TITLE
Fail when running mamba install instructions

### ISSUE THREAD

**Issue by ppxasjsm** [OpenBioSim/biosimspace_tutorials#7]
Hi, 

I am trying to install the tutorials on a debian system following the installation instructions...I am getting the following error:
```
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  15.9MB /  15.9MB                            0.5s
Extracting   (2) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━╸━━━━━       0 /       2 boost-cpp                 45.9scritical libmamba Can't create 'share/qt/3rd_party_licenses/qtwebengine/src/3rdparty/chromium/third_party/angle/src/third_party/compiler/LICENSE'
critical libmamba Can't create 'include/boost/geometry/geometries/polygon.hpp'
error    libmamba Error opening for reading "/home/homeblue01/5/dvs8tp45/mambaforge/pkgs/qt-main-5.15.8-h01ceb2d_13/info/index.json": No such file or directory
error    libmamba Error when extracting package: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
error    libmamba Error opening for reading "/home/homeblue01/5/dvs8tp45/mambaforge/pkgs/boost-cpp-1.78.0-h6582d0a_3/info/index.json": No such file or directory
qt-main-5.15.8-h01ceb2d_13.conda extraction failed
boost-cpp-1.78.0-h6582d0a_3.conda extraction failed
Found incorrect download: boost-cpp. Aborting

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/homeblue01/5/dvs8tp45/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/homeblue01/5/dvs8tp45/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/home/homeblue01/5/dvs8tp45/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/homeblue01/5/dvs8tp45/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/home/homeblue01/5/dvs8tp45/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 754, in do_call
        exit_code = install(args, parser, "install")
      File "/home/homeblue01/5/dvs8tp45/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 588, in install
        transaction.fetch_extract_packages()
    RuntimeError: Found incorrect download: boost-cpp. Aborting

`$ /home/homeblue01/5/dvs8tp45/mambaforge/bin/mamba install -n bsstutorials -c openbiosim -c conda-forge biosimspace=2023.3.0 gromacs=2023.1 ambertools=23.3`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/homeblue01/5/dvs8tp45/mambaforge/bin/conda
             CONDA_PREFIX=/home/homeblue01/5/dvs8tp45/mambaforge
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/homeblue01/5/dvs8tp45/mambaforge/bin/python
               CONDA_ROOT=/home/homeblue01/5/dvs8tp45/mambaforge
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                  MANPATH=:/opt/puppetlabs/puppet/share/man
                     PATH=/home/homeblue01/5/dvs8tp45/mambaforge/bin:/home/homeblue01/5/dvs8tp45
                          /mambaforge/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/us
                          r/games:/opt/local/bin:/opt/puppetlabs/bin:/opt/thinlinc/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base
    active env location : /home/homeblue01/5/dvs8tp45/mambaforge
            shell level : 1
       user config file : /home/homeblue01/5/dvs8tp45/.condarc
 populated config files : /home/homeblue01/5/dvs8tp45/mambaforge/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.10.0=0
                          __unix=0=0
       base environment : /home/homeblue01/5/dvs8tp45/mambaforge  (writable)
      conda av data dir : /home/homeblue01/5/dvs8tp45/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/openbiosim/linux-64
                          https://conda.anaconda.org/openbiosim/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/homeblue01/5/dvs8tp45/mambaforge/pkgs
                          /home/homeblue01/5/dvs8tp45/.conda/pkgs
       envs directories : /home/homeblue01/5/dvs8tp45/mambaforge/envs
                          /home/homeblue01/5/dvs8tp45/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.31.0 CPython/3.10.12 Linux/5.10.0-23-amd64 debian/11 glibc/2.31
                UID:GID : 29563:2700
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by jmichel80** [comment]
closing for inactivity
